/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista.Libro;

/**
 *
 * @author lenno
 */
public class buscarLibro extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(buscarLibro.class.getName());

    /**
     * Creates new form buscarLibro
     */
    public buscarLibro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlHeader = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        pnlCentro = new javax.swing.JPanel();
        pnlRegresar = new javax.swing.JPanel();
        btnVolver = new javax.swing.JButton();
        lbl1 = new javax.swing.JLabel();
        lbl2 = new javax.swing.JLabel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 20), new java.awt.Dimension(0, 10), new java.awt.Dimension(32767, 20));
        pnlBusqueda = new javax.swing.JPanel();
        cardBusqueda = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tipoBusquedaLibro = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        criterioBusquedaLibro = new javax.swing.JTextField();
        btnBuscarLibro = new javax.swing.JButton();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 20), new java.awt.Dimension(0, 10), new java.awt.Dimension(32767, 20));
        pnlResultado = new javax.swing.JPanel();
        cardResultado = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        pnlFooter = new javax.swing.JPanel();
        lblFooter = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(java.awt.Color.white);
        setResizable(false);

        pnlHeader.setBackground(new java.awt.Color(51, 51, 51));
        pnlHeader.setPreferredSize(new java.awt.Dimension(894, 54));
        pnlHeader.setLayout(new java.awt.BorderLayout());

        lblTitulo.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("BiblioSmart");
        lblTitulo.setAlignmentY(0.0F);
        lblTitulo.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 75, 1, 1));
        lblTitulo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblTitulo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnlHeader.add(lblTitulo, java.awt.BorderLayout.LINE_START);

        lblUsuario.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblUsuario.setForeground(new java.awt.Color(255, 255, 255));
        lblUsuario.setText("¡Bienvenido, Admin!");
        lblUsuario.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 75));
        pnlHeader.add(lblUsuario, java.awt.BorderLayout.LINE_END);

        getContentPane().add(pnlHeader, java.awt.BorderLayout.PAGE_START);

        pnlCentro.setBackground(java.awt.Color.white);
        pnlCentro.setLayout(new javax.swing.BoxLayout(pnlCentro, javax.swing.BoxLayout.Y_AXIS));

        pnlRegresar.setBackground(java.awt.Color.white);
        pnlRegresar.setMaximumSize(new java.awt.Dimension(32767, 40));
        pnlRegresar.setMinimumSize(new java.awt.Dimension(10, 1));
        pnlRegresar.setPreferredSize(new java.awt.Dimension(100, 40));
        pnlRegresar.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 70, 5));

        btnVolver.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnVolver.setText("Volver ");
        btnVolver.setBorder(null);
        btnVolver.setBorderPainted(false);
        btnVolver.setFocusPainted(false);
        btnVolver.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnVolver.setPreferredSize(new java.awt.Dimension(150, 30));
        btnVolver.addActionListener(this::btnVolverActionPerformed);
        pnlRegresar.add(btnVolver);

        pnlCentro.add(pnlRegresar);

        lbl1.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        lbl1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl1.setText("Gestion de Libros");
        lbl1.setToolTipText("");
        lbl1.setAlignmentX(0.5F);
        lbl1.setAlignmentY(0.0F);
        lbl1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnlCentro.add(lbl1);

        lbl2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl2.setText("Ingresa criterios de búsqueda para encontrar libros");
        lbl2.setAlignmentX(0.5F);
        lbl2.setAlignmentY(0.0F);
        pnlCentro.add(lbl2);
        pnlCentro.add(filler1);

        pnlBusqueda.setBackground(java.awt.Color.white);
        pnlBusqueda.setMaximumSize(new java.awt.Dimension(32767, 2000));
        pnlBusqueda.setMinimumSize(new java.awt.Dimension(10, 0));
        pnlBusqueda.setPreferredSize(new java.awt.Dimension(0, 105));
        pnlBusqueda.setRequestFocusEnabled(false);

        cardBusqueda.setBackground(java.awt.Color.white);
        cardBusqueda.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cardBusqueda.setPreferredSize(new java.awt.Dimension(500, 100));

        jLabel1.setText("Buscar por:");

        tipoBusquedaLibro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel2.setText("Criterios de búsqueda:");

        criterioBusquedaLibro.addActionListener(this::criterioBusquedaLibroActionPerformed);

        btnBuscarLibro.setText("Buscar");
        btnBuscarLibro.addActionListener(this::btnBuscarLibroActionPerformed);

        javax.swing.GroupLayout cardBusquedaLayout = new javax.swing.GroupLayout(cardBusqueda);
        cardBusqueda.setLayout(cardBusquedaLayout);
        cardBusquedaLayout.setHorizontalGroup(
            cardBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardBusquedaLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(cardBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tipoBusquedaLibro, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(cardBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(criterioBusquedaLibro)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 262, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(btnBuscarLibro)
                .addContainerGap(28, Short.MAX_VALUE))
        );
        cardBusquedaLayout.setVerticalGroup(
            cardBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardBusquedaLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(cardBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGap(14, 14, 14)
                .addGroup(cardBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(criterioBusquedaLibro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tipoBusquedaLibro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarLibro))
                .addGap(23, 23, 23))
        );

        pnlBusqueda.add(cardBusqueda);

        pnlCentro.add(pnlBusqueda);
        pnlCentro.add(filler2);

        pnlResultado.setBackground(java.awt.Color.white);

        cardResultado.setBackground(java.awt.Color.white);
        cardResultado.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cardResultado.setPreferredSize(new java.awt.Dimension(800, 180));
        cardResultado.setLayout(new java.awt.BorderLayout());

        jLabel3.setBackground(java.awt.Color.white);
        jLabel3.setText("Resultados de la busqueda");
        jLabel3.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        cardResultado.add(jLabel3, java.awt.BorderLayout.PAGE_START);

        jScrollPane1.setBackground(java.awt.Color.white);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setGridColor(java.awt.Color.black);
        jTable1.setSelectionBackground(java.awt.Color.black);
        jScrollPane1.setViewportView(jTable1);

        cardResultado.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        pnlResultado.add(cardResultado);

        pnlCentro.add(pnlResultado);

        getContentPane().add(pnlCentro, java.awt.BorderLayout.CENTER);

        pnlFooter.setBackground(new java.awt.Color(51, 51, 51));
        pnlFooter.setPreferredSize(new java.awt.Dimension(894, 54));
        pnlFooter.setLayout(new java.awt.BorderLayout());

        lblFooter.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblFooter.setForeground(java.awt.Color.white);
        lblFooter.setText("Sistema de Gestión Bibliotecaria");
        lblFooter.setAlignmentY(0.0F);
        lblFooter.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 40, 1, 1));
        lblFooter.setFocusable(false);
        lblFooter.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        pnlFooter.add(lblFooter, java.awt.BorderLayout.WEST);

        getContentPane().add(pnlFooter, java.awt.BorderLayout.SOUTH);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnBuscarLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarLibroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarLibroActionPerformed

    private void criterioBusquedaLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_criterioBusquedaLibroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_criterioBusquedaLibroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new buscarLibro().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarLibro;
    private javax.swing.JButton btnVolver;
    private javax.swing.JPanel cardBusqueda;
    private javax.swing.JPanel cardResultado;
    private javax.swing.JTextField criterioBusquedaLibro;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lbl1;
    private javax.swing.JLabel lbl2;
    private javax.swing.JLabel lblFooter;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JPanel pnlBusqueda;
    private javax.swing.JPanel pnlCentro;
    private javax.swing.JPanel pnlFooter;
    private javax.swing.JPanel pnlHeader;
    private javax.swing.JPanel pnlRegresar;
    private javax.swing.JPanel pnlResultado;
    private javax.swing.JComboBox<String> tipoBusquedaLibro;
    // End of variables declaration//GEN-END:variables
}
