/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista.Libro;

import java.awt.Color;
import javax.swing.BorderFactory;

/**
 *
 * @author lenno
 */
public class FrmGestionLibros extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmGestionLibros.class.getName());

    /**
     * Creates new form FrmGestionLibros
     */
    public FrmGestionLibros() {
        initComponents();
        setSize(900, 600);
        setMinimumSize(new java.awt.Dimension(900, 600));
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelHeader = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        panelContenido = new javax.swing.JPanel();
        panelRegresar = new javax.swing.JPanel();
        btnRegresarMenuPrincipal = new javax.swing.JButton();
        lblGestionLibros = new javax.swing.JLabel();
        lblDescripcion = new javax.swing.JLabel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 45), new java.awt.Dimension(0, 45), new java.awt.Dimension(32767, 45));
        panelOpciones = new javax.swing.JPanel();
        cardRegistrar = new javax.swing.JPanel();
        panelBoton2 = new javax.swing.JPanel();
        btnPanelRegistrar = new javax.swing.JButton();
        panelTexto2 = new javax.swing.JPanel();
        lblEliminar2 = new javax.swing.JLabel();
        lblEliminarDescripcion4 = new javax.swing.JLabel();
        lblEliminarDescripcion5 = new javax.swing.JLabel();
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(15, 32767));
        cardPanelBuscar = new javax.swing.JPanel();
        panelBoton1 = new javax.swing.JPanel();
        btnPanelBuscar = new javax.swing.JButton();
        panelTexto1 = new javax.swing.JPanel();
        lblEliminar1 = new javax.swing.JLabel();
        lblEliminarDescripcion2 = new javax.swing.JLabel();
        lblEliminarDescripcion3 = new javax.swing.JLabel();
        panelOpciones1 = new javax.swing.JPanel();
        cardEliminar = new javax.swing.JPanel();
        panelTextoEliminar = new javax.swing.JPanel();
        lblEliminar = new javax.swing.JLabel();
        lblEliminarDescripcion = new javax.swing.JLabel();
        lblEliminarDescripcion1 = new javax.swing.JLabel();
        panelBotonEliminar = new javax.swing.JPanel();
        btnPanelEliminar = new javax.swing.JButton();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 25), new java.awt.Dimension(0, 25), new java.awt.Dimension(32767, 10));
        panelFooter = new javax.swing.JPanel();
        lblFooter = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("BiblioSmart");
        setBackground(java.awt.Color.white);
        setMaximumSize(new java.awt.Dimension(910, 568));
        setMinimumSize(new java.awt.Dimension(910, 568));
        setPreferredSize(new java.awt.Dimension(910, 568));
        setResizable(false);

        panelHeader.setBackground(new java.awt.Color(51, 51, 51));
        panelHeader.setMaximumSize(new java.awt.Dimension(910, 54));
        panelHeader.setMinimumSize(new java.awt.Dimension(910, 54));
        panelHeader.setPreferredSize(new java.awt.Dimension(910, 54));
        panelHeader.setLayout(new java.awt.BorderLayout());

        lblTitulo.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("BiblioSmart");
        lblTitulo.setAlignmentY(0.0F);
        lblTitulo.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 75, 1, 1));
        lblTitulo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblTitulo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        panelHeader.add(lblTitulo, java.awt.BorderLayout.LINE_START);

        lblUsuario.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblUsuario.setForeground(new java.awt.Color(255, 255, 255));
        lblUsuario.setText("¡Bienvenido, Admin!");
        lblUsuario.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 75));
        panelHeader.add(lblUsuario, java.awt.BorderLayout.LINE_END);

        getContentPane().add(panelHeader, java.awt.BorderLayout.NORTH);

        BorderFactory.createEmptyBorder(20, 40, 20, 40);
        panelContenido.setBackground(new java.awt.Color(255, 255, 255));
        panelContenido.setMaximumSize(new java.awt.Dimension(32767, 250));
        panelContenido.setMinimumSize(new java.awt.Dimension(800, 250));
        panelContenido.setPreferredSize(new java.awt.Dimension(800, 250));
        panelContenido.setLayout(new javax.swing.BoxLayout(panelContenido, javax.swing.BoxLayout.Y_AXIS));

        panelRegresar.setBackground(java.awt.Color.white);
        panelRegresar.setMaximumSize(new java.awt.Dimension(32767, 40));
        panelRegresar.setMinimumSize(new java.awt.Dimension(10, 1));
        panelRegresar.setPreferredSize(new java.awt.Dimension(100, 1));
        panelRegresar.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 70, 5));

        btnRegresarMenuPrincipal.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnRegresarMenuPrincipal.setText("Volver al menú principal");
        btnRegresarMenuPrincipal.setBorder(null);
        btnRegresarMenuPrincipal.setBorderPainted(false);
        btnRegresarMenuPrincipal.setFocusPainted(false);
        btnRegresarMenuPrincipal.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnRegresarMenuPrincipal.setPreferredSize(new java.awt.Dimension(150, 30));
        btnRegresarMenuPrincipal.addActionListener(this::btnRegresarMenuPrincipalActionPerformed);
        panelRegresar.add(btnRegresarMenuPrincipal);

        panelContenido.add(panelRegresar);

        lblGestionLibros.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        lblGestionLibros.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblGestionLibros.setText("Gestion de Libros");
        lblGestionLibros.setToolTipText("");
        lblGestionLibros.setAlignmentX(0.5F);
        lblGestionLibros.setAlignmentY(0.0F);
        lblGestionLibros.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        panelContenido.add(lblGestionLibros);

        lblDescripcion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblDescripcion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDescripcion.setText("Administra el catálogo de libros de la biblioteca");
        lblDescripcion.setAlignmentX(0.5F);
        lblDescripcion.setAlignmentY(0.0F);
        panelContenido.add(lblDescripcion);
        panelContenido.add(filler1);

        panelOpciones.setBackground(Color.WHITE);
        panelOpciones.setBackground(java.awt.Color.white);
        panelOpciones.setMaximumSize(new java.awt.Dimension(800, 110));
        panelOpciones.setMinimumSize(new java.awt.Dimension(800, 110));
        panelOpciones.setName(""); // NOI18N
        panelOpciones.setPreferredSize(new java.awt.Dimension(800, 110));

        cardRegistrar.setBackground(java.awt.Color.white);
        cardRegistrar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        cardRegistrar.setMaximumSize(new java.awt.Dimension(320, 80));
        cardRegistrar.setMinimumSize(new java.awt.Dimension(320, 100));
        cardRegistrar.setPreferredSize(new java.awt.Dimension(320, 100));
        cardRegistrar.setLayout(new java.awt.BorderLayout());

        panelBoton2.setBackground(java.awt.Color.white);

        btnPanelRegistrar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnPanelRegistrar.setText("+");
        btnPanelRegistrar.setAlignmentY(0.0F);
        btnPanelRegistrar.setBorderPainted(false);
        btnPanelRegistrar.setFocusPainted(false);
        btnPanelRegistrar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPanelRegistrar.setMaximumSize(new java.awt.Dimension(39, 37));
        btnPanelRegistrar.setMinimumSize(new java.awt.Dimension(39, 37));
        btnPanelRegistrar.setPreferredSize(new java.awt.Dimension(39, 37));
        btnPanelRegistrar.setRolloverEnabled(false);
        btnPanelRegistrar.addActionListener(this::btnPanelRegistrarActionPerformed);

        javax.swing.GroupLayout panelBoton2Layout = new javax.swing.GroupLayout(panelBoton2);
        panelBoton2.setLayout(panelBoton2Layout);
        panelBoton2Layout.setHorizontalGroup(
            panelBoton2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBoton2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnPanelRegistrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelBoton2Layout.setVerticalGroup(
            panelBoton2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBoton2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(btnPanelRegistrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );

        cardRegistrar.add(panelBoton2, java.awt.BorderLayout.EAST);

        panelTexto2.setBackground(java.awt.Color.white);

        lblEliminar2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblEliminar2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEliminar2.setText("Registrar Libros");

        lblEliminarDescripcion4.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblEliminarDescripcion4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEliminarDescripcion4.setText("Permite registrar nuevos");
        lblEliminarDescripcion4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblEliminarDescripcion4.setMaximumSize(new java.awt.Dimension(0, 0));
        lblEliminarDescripcion4.setMinimumSize(new java.awt.Dimension(0, 0));
        lblEliminarDescripcion4.setPreferredSize(new java.awt.Dimension(0, 0));

        lblEliminarDescripcion5.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblEliminarDescripcion5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEliminarDescripcion5.setText("libros en el sistema");
        lblEliminarDescripcion5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblEliminarDescripcion5.setMaximumSize(new java.awt.Dimension(0, 0));
        lblEliminarDescripcion5.setMinimumSize(new java.awt.Dimension(0, 0));
        lblEliminarDescripcion5.setPreferredSize(new java.awt.Dimension(0, 0));

        javax.swing.GroupLayout panelTexto2Layout = new javax.swing.GroupLayout(panelTexto2);
        panelTexto2.setLayout(panelTexto2Layout);
        panelTexto2Layout.setHorizontalGroup(
            panelTexto2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblEliminarDescripcion5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblEliminarDescripcion4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblEliminar2, javax.swing.GroupLayout.DEFAULT_SIZE, 267, Short.MAX_VALUE)
        );
        panelTexto2Layout.setVerticalGroup(
            panelTexto2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTexto2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(lblEliminar2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblEliminarDescripcion4, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblEliminarDescripcion5, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        cardRegistrar.add(panelTexto2, java.awt.BorderLayout.CENTER);

        panelOpciones.add(cardRegistrar);
        panelOpciones.add(filler3);

        cardPanelBuscar.setBackground(java.awt.Color.white);
        cardPanelBuscar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        cardPanelBuscar.setMaximumSize(new java.awt.Dimension(320, 80));
        cardPanelBuscar.setMinimumSize(new java.awt.Dimension(320, 100));
        cardPanelBuscar.setPreferredSize(new java.awt.Dimension(320, 100));
        cardPanelBuscar.setLayout(new java.awt.BorderLayout());

        panelBoton1.setBackground(java.awt.Color.white);

        btnPanelBuscar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnPanelBuscar.setText("+");
        btnPanelBuscar.setAlignmentY(0.0F);
        btnPanelBuscar.setBorderPainted(false);
        btnPanelBuscar.setFocusPainted(false);
        btnPanelBuscar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPanelBuscar.setMaximumSize(new java.awt.Dimension(39, 37));
        btnPanelBuscar.setMinimumSize(new java.awt.Dimension(39, 37));
        btnPanelBuscar.setPreferredSize(new java.awt.Dimension(39, 37));
        btnPanelBuscar.setRolloverEnabled(false);
        btnPanelBuscar.addActionListener(this::btnPanelBuscarActionPerformed);

        javax.swing.GroupLayout panelBoton1Layout = new javax.swing.GroupLayout(panelBoton1);
        panelBoton1.setLayout(panelBoton1Layout);
        panelBoton1Layout.setHorizontalGroup(
            panelBoton1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBoton1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnPanelBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelBoton1Layout.setVerticalGroup(
            panelBoton1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBoton1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(btnPanelBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );

        cardPanelBuscar.add(panelBoton1, java.awt.BorderLayout.EAST);

        panelTexto1.setBackground(java.awt.Color.white);

        lblEliminar1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblEliminar1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEliminar1.setText("Buscar Libros");

        lblEliminarDescripcion2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblEliminarDescripcion2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEliminarDescripcion2.setText("Permite buscar y consultar");
        lblEliminarDescripcion2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblEliminarDescripcion2.setMaximumSize(new java.awt.Dimension(0, 0));
        lblEliminarDescripcion2.setMinimumSize(new java.awt.Dimension(0, 0));
        lblEliminarDescripcion2.setPreferredSize(new java.awt.Dimension(0, 0));

        lblEliminarDescripcion3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblEliminarDescripcion3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEliminarDescripcion3.setText("libros en el catálogo");
        lblEliminarDescripcion3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblEliminarDescripcion3.setMaximumSize(new java.awt.Dimension(0, 0));
        lblEliminarDescripcion3.setMinimumSize(new java.awt.Dimension(0, 0));
        lblEliminarDescripcion3.setPreferredSize(new java.awt.Dimension(0, 0));

        javax.swing.GroupLayout panelTexto1Layout = new javax.swing.GroupLayout(panelTexto1);
        panelTexto1.setLayout(panelTexto1Layout);
        panelTexto1Layout.setHorizontalGroup(
            panelTexto1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblEliminarDescripcion3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblEliminarDescripcion2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblEliminar1, javax.swing.GroupLayout.DEFAULT_SIZE, 267, Short.MAX_VALUE)
        );
        panelTexto1Layout.setVerticalGroup(
            panelTexto1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTexto1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(lblEliminar1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblEliminarDescripcion2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblEliminarDescripcion3, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        cardPanelBuscar.add(panelTexto1, java.awt.BorderLayout.CENTER);

        panelOpciones.add(cardPanelBuscar);

        panelContenido.add(panelOpciones);

        panelOpciones1.setBackground(Color.WHITE);
        panelOpciones1.setBackground(java.awt.Color.white);
        panelOpciones1.setMaximumSize(new java.awt.Dimension(800, 110));
        panelOpciones1.setMinimumSize(new java.awt.Dimension(800, 110));
        panelOpciones1.setPreferredSize(new java.awt.Dimension(800, 110));

        cardEliminar.setBackground(java.awt.Color.white);
        cardEliminar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        cardEliminar.setMaximumSize(new java.awt.Dimension(320, 80));
        cardEliminar.setMinimumSize(new java.awt.Dimension(320, 100));
        cardEliminar.setPreferredSize(new java.awt.Dimension(320, 100));
        cardEliminar.setLayout(new java.awt.BorderLayout());

        panelTextoEliminar.setBackground(java.awt.Color.white);

        lblEliminar.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblEliminar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEliminar.setText("Eliminar Libros");

        lblEliminarDescripcion.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblEliminarDescripcion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEliminarDescripcion.setText("Permite eliminar libros");
        lblEliminarDescripcion.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblEliminarDescripcion.setMaximumSize(new java.awt.Dimension(0, 0));
        lblEliminarDescripcion.setMinimumSize(new java.awt.Dimension(0, 0));
        lblEliminarDescripcion.setPreferredSize(new java.awt.Dimension(0, 0));

        lblEliminarDescripcion1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblEliminarDescripcion1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEliminarDescripcion1.setText("existentes en el sistema ");
        lblEliminarDescripcion1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblEliminarDescripcion1.setMaximumSize(new java.awt.Dimension(0, 0));
        lblEliminarDescripcion1.setMinimumSize(new java.awt.Dimension(0, 0));
        lblEliminarDescripcion1.setPreferredSize(new java.awt.Dimension(0, 0));

        javax.swing.GroupLayout panelTextoEliminarLayout = new javax.swing.GroupLayout(panelTextoEliminar);
        panelTextoEliminar.setLayout(panelTextoEliminarLayout);
        panelTextoEliminarLayout.setHorizontalGroup(
            panelTextoEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblEliminarDescripcion1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblEliminarDescripcion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, 267, Short.MAX_VALUE)
        );
        panelTextoEliminarLayout.setVerticalGroup(
            panelTextoEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTextoEliminarLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(lblEliminar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblEliminarDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblEliminarDescripcion1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        cardEliminar.add(panelTextoEliminar, java.awt.BorderLayout.CENTER);

        panelBotonEliminar.setBackground(java.awt.Color.white);

        btnPanelEliminar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnPanelEliminar.setText("+");
        btnPanelEliminar.setAlignmentY(0.0F);
        btnPanelEliminar.setBorderPainted(false);
        btnPanelEliminar.setFocusPainted(false);
        btnPanelEliminar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPanelEliminar.setMaximumSize(new java.awt.Dimension(39, 37));
        btnPanelEliminar.setMinimumSize(new java.awt.Dimension(39, 37));
        btnPanelEliminar.setPreferredSize(new java.awt.Dimension(39, 37));
        btnPanelEliminar.setRolloverEnabled(false);
        btnPanelEliminar.addActionListener(this::btnPanelEliminarActionPerformed);

        javax.swing.GroupLayout panelBotonEliminarLayout = new javax.swing.GroupLayout(panelBotonEliminar);
        panelBotonEliminar.setLayout(panelBotonEliminarLayout);
        panelBotonEliminarLayout.setHorizontalGroup(
            panelBotonEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBotonEliminarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnPanelEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelBotonEliminarLayout.setVerticalGroup(
            panelBotonEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBotonEliminarLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(btnPanelEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );

        cardEliminar.add(panelBotonEliminar, java.awt.BorderLayout.EAST);

        panelOpciones1.add(cardEliminar);

        panelContenido.add(panelOpciones1);
        panelContenido.add(filler2);

        getContentPane().add(panelContenido, java.awt.BorderLayout.CENTER);

        panelFooter.setBackground(new java.awt.Color(51, 51, 51));
        panelFooter.setPreferredSize(new java.awt.Dimension(900, 40));
        panelFooter.setLayout(new java.awt.BorderLayout());

        lblFooter.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblFooter.setForeground(java.awt.Color.white);
        lblFooter.setText("Sistema de Gestión Bibliotecaria");
        lblFooter.setAlignmentY(0.0F);
        lblFooter.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 40, 1, 1));
        lblFooter.setFocusable(false);
        lblFooter.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        panelFooter.add(lblFooter, java.awt.BorderLayout.WEST);

        getContentPane().add(panelFooter, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPanelEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPanelEliminarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPanelEliminarActionPerformed

    private void btnPanelBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPanelBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPanelBuscarActionPerformed

    private void btnPanelRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPanelRegistrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPanelRegistrarActionPerformed

    private void btnRegresarMenuPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarMenuPrincipalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegresarMenuPrincipalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmGestionLibros().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPanelBuscar;
    private javax.swing.JButton btnPanelEliminar;
    private javax.swing.JButton btnPanelRegistrar;
    private javax.swing.JButton btnRegresarMenuPrincipal;
    private javax.swing.JPanel cardEliminar;
    private javax.swing.JPanel cardPanelBuscar;
    private javax.swing.JPanel cardRegistrar;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.JLabel lblDescripcion;
    private javax.swing.JLabel lblEliminar;
    private javax.swing.JLabel lblEliminar1;
    private javax.swing.JLabel lblEliminar2;
    private javax.swing.JLabel lblEliminarDescripcion;
    private javax.swing.JLabel lblEliminarDescripcion1;
    private javax.swing.JLabel lblEliminarDescripcion2;
    private javax.swing.JLabel lblEliminarDescripcion3;
    private javax.swing.JLabel lblEliminarDescripcion4;
    private javax.swing.JLabel lblEliminarDescripcion5;
    private javax.swing.JLabel lblFooter;
    private javax.swing.JLabel lblGestionLibros;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JPanel panelBoton1;
    private javax.swing.JPanel panelBoton2;
    private javax.swing.JPanel panelBotonEliminar;
    private javax.swing.JPanel panelContenido;
    private javax.swing.JPanel panelFooter;
    private javax.swing.JPanel panelHeader;
    private javax.swing.JPanel panelOpciones;
    private javax.swing.JPanel panelOpciones1;
    private javax.swing.JPanel panelRegresar;
    private javax.swing.JPanel panelTexto1;
    private javax.swing.JPanel panelTexto2;
    private javax.swing.JPanel panelTextoEliminar;
    // End of variables declaration//GEN-END:variables
}
