/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista.Libro;

/**
 *
 * @author HP OMEN
 */
public class prestarLibros extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(prestarLibros.class.getName());

    /**
     * Creates new form prestarLibros
     */
    public prestarLibros() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnVolver = new javax.swing.JButton();
        lbl1 = new javax.swing.JLabel();
        cardBusqueda = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        criterioBusquedaLibro = new javax.swing.JTextField();
        criterioBusquedaLibro1 = new javax.swing.JTextField();
        criterioBusquedaLibro2 = new javax.swing.JTextField();
        criterioBusquedaLibro3 = new javax.swing.JTextField();
        criterioBusquedaLibro4 = new javax.swing.JTextField();
        criterioBusquedaLibro5 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        btnBuscarLibro1 = new javax.swing.JButton();
        btnBuscarLibro2 = new javax.swing.JButton();
        btnBuscarLibro = new javax.swing.JButton();
        pnlFooter = new javax.swing.JPanel();
        lblFooter = new javax.swing.JLabel();
        pnlHeader = new javax.swing.JPanel();
        lblTitulo1 = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnVolver.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnVolver.setText("Volver ");
        btnVolver.setBorder(null);
        btnVolver.setBorderPainted(false);
        btnVolver.setFocusPainted(false);
        btnVolver.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnVolver.setPreferredSize(new java.awt.Dimension(150, 30));
        btnVolver.addActionListener(this::btnVolverActionPerformed);

        lbl1.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        lbl1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl1.setText("Gestion de Libros");
        lbl1.setToolTipText("");
        lbl1.setAlignmentX(0.5F);
        lbl1.setAlignmentY(0.0F);
        lbl1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        cardBusqueda.setBackground(java.awt.Color.white);
        cardBusqueda.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cardBusqueda.setPreferredSize(new java.awt.Dimension(500, 100));

        jLabel2.setText("Cedula del Cliente");

        criterioBusquedaLibro.addActionListener(this::criterioBusquedaLibroActionPerformed);

        criterioBusquedaLibro1.addActionListener(this::criterioBusquedaLibro1ActionPerformed);

        criterioBusquedaLibro2.addActionListener(this::criterioBusquedaLibro2ActionPerformed);

        criterioBusquedaLibro3.addActionListener(this::criterioBusquedaLibro3ActionPerformed);

        criterioBusquedaLibro4.addActionListener(this::criterioBusquedaLibro4ActionPerformed);

        criterioBusquedaLibro5.addActionListener(this::criterioBusquedaLibro5ActionPerformed);

        jLabel3.setText("Titulo del Libro");

        jLabel4.setText("Codigo del Libro");

        jLabel5.setText("Fecha Limite de Devoluvion");

        jLabel6.setText("Nombre del Cliente");

        jLabel7.setText("Fecha de Prestamos");

        jLabel8.setText("Estado del Prestamo");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout cardBusquedaLayout = new javax.swing.GroupLayout(cardBusqueda);
        cardBusqueda.setLayout(cardBusquedaLayout);
        cardBusquedaLayout.setHorizontalGroup(
            cardBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardBusquedaLayout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addGroup(cardBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cardBusquedaLayout.createSequentialGroup()
                        .addComponent(criterioBusquedaLibro4, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(cardBusquedaLayout.createSequentialGroup()
                        .addGroup(cardBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(criterioBusquedaLibro1, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(cardBusquedaLayout.createSequentialGroup()
                                .addGroup(cardBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(criterioBusquedaLibro3, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(criterioBusquedaLibro5, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(104, 104, 104)
                                .addGroup(cardBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(criterioBusquedaLibro2)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(criterioBusquedaLibro)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBox1, 0, 262, Short.MAX_VALUE))))
                        .addContainerGap(109, Short.MAX_VALUE))))
        );
        cardBusquedaLayout.setVerticalGroup(
            cardBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardBusquedaLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(cardBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(cardBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(criterioBusquedaLibro1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(criterioBusquedaLibro2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(cardBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(cardBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(criterioBusquedaLibro3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(criterioBusquedaLibro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(cardBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(cardBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(criterioBusquedaLibro5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(criterioBusquedaLibro4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        btnBuscarLibro1.setText("Registrar Prestamo");
        btnBuscarLibro1.addActionListener(this::btnBuscarLibro1ActionPerformed);

        btnBuscarLibro2.setText("Limpiar");
        btnBuscarLibro2.addActionListener(this::btnBuscarLibro2ActionPerformed);

        btnBuscarLibro.setText("Cancelar Prestamo");
        btnBuscarLibro.addActionListener(this::btnBuscarLibroActionPerformed);

        pnlFooter.setBackground(new java.awt.Color(51, 51, 51));
        pnlFooter.setPreferredSize(new java.awt.Dimension(894, 54));
        pnlFooter.setLayout(new java.awt.BorderLayout());

        lblFooter.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblFooter.setForeground(java.awt.Color.white);
        lblFooter.setText("Sistema de Gestión Bibliotecaria");
        lblFooter.setAlignmentY(0.0F);
        lblFooter.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 40, 1, 1));
        lblFooter.setFocusable(false);
        lblFooter.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        pnlFooter.add(lblFooter, java.awt.BorderLayout.WEST);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addComponent(btnBuscarLibro1)
                .addGap(184, 184, 184)
                .addComponent(btnBuscarLibro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnBuscarLibro2)
                .addGap(68, 68, 68))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cardBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 857, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(184, 184, 184)
                .addComponent(lbl1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(pnlFooter, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cardBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBuscarLibro)
                    .addComponent(btnBuscarLibro2)
                    .addComponent(btnBuscarLibro1))
                .addGap(19, 19, 19)
                .addComponent(pnlFooter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pnlHeader.setBackground(new java.awt.Color(51, 51, 51));
        pnlHeader.setPreferredSize(new java.awt.Dimension(894, 54));
        pnlHeader.setLayout(new java.awt.BorderLayout());

        lblTitulo1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lblTitulo1.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo1.setText("BiblioSmart");
        lblTitulo1.setAlignmentY(0.0F);
        lblTitulo1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 75, 1, 1));
        lblTitulo1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblTitulo1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnlHeader.add(lblTitulo1, java.awt.BorderLayout.LINE_START);

        lblUsuario.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblUsuario.setForeground(new java.awt.Color(255, 255, 255));
        lblUsuario.setText("¡Bienvenido, Admin!");
        lblUsuario.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 75));
        pnlHeader.add(lblUsuario, java.awt.BorderLayout.LINE_END);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pnlHeader, javax.swing.GroupLayout.DEFAULT_SIZE, 910, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVolverActionPerformed

    private void criterioBusquedaLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_criterioBusquedaLibroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_criterioBusquedaLibroActionPerformed

    private void btnBuscarLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarLibroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarLibroActionPerformed

    private void btnBuscarLibro1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarLibro1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarLibro1ActionPerformed

    private void btnBuscarLibro2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarLibro2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarLibro2ActionPerformed

    private void criterioBusquedaLibro1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_criterioBusquedaLibro1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_criterioBusquedaLibro1ActionPerformed

    private void criterioBusquedaLibro2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_criterioBusquedaLibro2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_criterioBusquedaLibro2ActionPerformed

    private void criterioBusquedaLibro3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_criterioBusquedaLibro3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_criterioBusquedaLibro3ActionPerformed

    private void criterioBusquedaLibro4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_criterioBusquedaLibro4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_criterioBusquedaLibro4ActionPerformed

    private void criterioBusquedaLibro5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_criterioBusquedaLibro5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_criterioBusquedaLibro5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new prestarLibros().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarLibro;
    private javax.swing.JButton btnBuscarLibro1;
    private javax.swing.JButton btnBuscarLibro2;
    private javax.swing.JButton btnVolver;
    private javax.swing.JPanel cardBusqueda;
    private javax.swing.JTextField criterioBusquedaLibro;
    private javax.swing.JTextField criterioBusquedaLibro1;
    private javax.swing.JTextField criterioBusquedaLibro2;
    private javax.swing.JTextField criterioBusquedaLibro3;
    private javax.swing.JTextField criterioBusquedaLibro4;
    private javax.swing.JTextField criterioBusquedaLibro5;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl1;
    private javax.swing.JLabel lblFooter;
    private javax.swing.JLabel lblTitulo1;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JPanel pnlFooter;
    private javax.swing.JPanel pnlHeader;
    // End of variables declaration//GEN-END:variables
}
