/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Controlador.UsuarioControlador;
import Modelo.Usuario;
import java.util.Properties;
import javax.mail.Message;
import javax.mail.PasswordAuthentication;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import javax.swing.JOptionPane;
public class FrmRecuperacion extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmRecuperacion.class.getName());

    /**
     * Creates new form FrmRecuperacion
     */
    public FrmRecuperacion() {
        initComponents();
        setLocationRelativeTo(null);
          setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
    
    addWindowListener(new java.awt.event.WindowAdapter() {
        @Override
        public void windowClosing(java.awt.event.WindowEvent e) {
            new FrmLogin().setVisible(true);
            dispose();
        }
    });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnRecuperar = new javax.swing.JButton();
        campoCedula = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        campoCorreo = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnRecuperar.setText("Recuperar");
        btnRecuperar.addActionListener(this::btnRecuperarActionPerformed);

        campoCedula.addActionListener(this::campoCedulaActionPerformed);

        jLabel1.setText("Ingrese su cedula:");

        jLabel2.setText("Ingrese su correo asociado:");

        campoCorreo.addActionListener(this::campoCorreoActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(campoCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campoCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(btnRecuperar, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(74, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(campoCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(campoCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnRecuperar)
                .addContainerGap(96, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRecuperarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecuperarActionPerformed
          String cedula = campoCedula.getText().trim();
    String correo = campoCorreo.getText().trim();

    if (cedula.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Ingrese la cedula");
        campoCedula.requestFocus();
        return;
    }
    if (correo.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Ingrese el correo");
        campoCorreo.requestFocus();
        return;
    }
    if (!cedula.matches("[0-9]+")) {
        JOptionPane.showMessageDialog(this, "La cedula solo debe contener numeros");
        campoCedula.setText("");
        campoCedula.requestFocus();
        return;
    }
    if (!correo.matches("^[A-Za-z0-9+_.-]+@(.+)$")) {
        JOptionPane.showMessageDialog(this, "Correo invalido");
        campoCorreo.setText("");
        campoCorreo.requestFocus();
        return;
    }

    // ✅ Busca en el JSON — NO hay datos quemados
    UsuarioControlador controlador = new UsuarioControlador();
    Usuario encontrado = controlador.buscarPorCedulaYCorreo(cedula, correo);

    if (encontrado != null) {
        // Envía la contraseña real del usuario registrado
        enviarCorreo(encontrado.getCorreo(), encontrado.getNombre(), 
                     encontrado.getContrasena());
    } else {
        JOptionPane.showMessageDialog(this,
                "No se encontro ningun usuario con esa cedula y correo.",
                "Usuario no encontrado",
                JOptionPane.ERROR_MESSAGE);
        campoCedula.setText("");
        campoCorreo.setText("");
        campoCedula.requestFocus();
    }
    }                      

 private void enviarCorreo(String destino, String nombre, String contrasena) {
final String remitente = "ivanyacelga001@gmail.com";
final String claveApp  = "zkfzwsfxfxwoiocf";

Properties props = new Properties();
props.put("mail.smtp.host", "smtp.gmail.com");
props.put("mail.smtp.port", "587");
props.put("mail.smtp.auth", "true");
props.put("mail.smtp.starttls.enable", "true");
props.put("mail.smtp.starttls.required", "true");
props.put("mail.smtp.ssl.trust", "smtp.gmail.com");
props.put("mail.smtp.ssl.protocols", "TLSv1.2");
props.put("mail.debug", "true");
props.put("mail.smtp.localhost", "biblioteca.sistema");

    Session session = Session.getInstance(props, new javax.mail.Authenticator() {
        protected PasswordAuthentication getPasswordAuthentication() {
            return new PasswordAuthentication(remitente, claveApp);
        }
    });

    try {
        Message mensaje = new MimeMessage(session);
        mensaje.setFrom(new InternetAddress(remitente));
        mensaje.setRecipients(Message.RecipientType.TO, InternetAddress.parse(destino));
        mensaje.setSubject("Recuperacion de contrasena - Sistema Biblioteca");
        mensaje.setText(
                "Hola " + nombre + ",\n\n"
                + "Tu contrasena es: " + contrasena + "\n\n"
                + "Sistema de Gestion Biblioteca"
        );

        Transport.send(mensaje);

        JOptionPane.showMessageDialog(this,
                "Correo enviado a: " + destino,
                "Exito",
                JOptionPane.INFORMATION_MESSAGE);

        // Volver al login
        new FrmLogin().setVisible(true);
        this.dispose();
        

    } catch (Exception e) {
        // Mostrar error completo para diagnosticar
    JOptionPane.showMessageDialog(this,
            "Error completo:\n" + e.toString(),
            "Error",
            JOptionPane.ERROR_MESSAGE);
    e.printStackTrace(); // imprime en consola de NetBeans
}
    }//GEN-LAST:event_btnRecuperarActionPerformed

    private void campoCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoCorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoCorreoActionPerformed

    private void campoCedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoCedulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoCedulaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmRecuperacion().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRecuperar;
    private javax.swing.JTextField campoCedula;
    private javax.swing.JTextField campoCorreo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
