/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Controlador.UsuarioControlador;
import Modelo.Usuario;

// ─── Imports Java ───
import javax.swing.JOptionPane;

public class FrmRegistrarse extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmRegistrarse.class.getName());

    /**
     * Creates new form FrmRegistrarse
     */
    public FrmRegistrarse() {
        initComponents();
        setLocationRelativeTo(null);
         setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
    
    addWindowListener(new java.awt.event.WindowAdapter() {
        @Override
        public void windowClosing(java.awt.event.WindowEvent e) {
            new FrmLogin().setVisible(true);
            dispose();
        }
    });


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cpNombre1 = new javax.swing.JTextField();
        cpUsuario1 = new javax.swing.JTextField();
        cpCedula = new javax.swing.JTextField();
        cpCorreo = new javax.swing.JTextField();
        btnRegistrar = new javax.swing.JButton();
        cpContraseña = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setText("Ingrese su Nombre:");

        jLabel2.setText("Ingrese un Usuario:");

        jLabel3.setText("Ingrese una Contraseña:");

        jLabel4.setText("Ingrese su Cedula de Identidad:");

        jLabel5.setText("Ingrese un Correo electronico");

        cpNombre1.addActionListener(this::cpNombre1ActionPerformed);

        cpUsuario1.addActionListener(this::cpUsuario1ActionPerformed);

        cpCedula.addActionListener(this::cpCedulaActionPerformed);

        cpCorreo.addActionListener(this::cpCorreoActionPerformed);

        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(this::btnRegistrarActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRegistrar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cpNombre1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cpUsuario1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cpCorreo)
                    .addComponent(cpCedula)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(0, 334, Short.MAX_VALUE))
                    .addComponent(cpContraseña))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cpNombre1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cpUsuario1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cpContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cpCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cpCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(btnRegistrar)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cpNombre1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cpNombre1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cpNombre1ActionPerformed

    private void cpUsuario1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cpUsuario1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cpUsuario1ActionPerformed

    private void cpCedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cpCedulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cpCedulaActionPerformed

    private void cpCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cpCorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cpCorreoActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        // TODO add your handling code here:

        // 1. Obtener datos del formulario
        String nombre = cpNombre1.getText().trim();
        String usuario = cpUsuario1.getText().trim();
        String contrasena = String.valueOf(cpContraseña.getPassword()).trim();
        String cedula = cpCedula.getText().trim();
        String correo = cpCorreo.getText().trim();

        // 2. Validar campos vacíos
        if (nombre.isEmpty() || usuario.isEmpty() || contrasena.isEmpty()
                || cedula.isEmpty() || correo.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Todos los campos son obligatorios.",
                    "Aviso",
                    javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        // 3. Crear objeto Modelo
        Modelo.Usuario nuevoUsuario = new Modelo.Usuario(
                nombre, usuario, contrasena, cedula, correo
        );

        // 4. Llamar al Controlador
        Controlador.UsuarioControlador controlador = new Controlador.UsuarioControlador();
        String resultado = controlador.registrarUsuario(nuevoUsuario);

        // 5. Evaluar resultado
        if (resultado.equals("OK")) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Usuario registrado exitosamente.",
                    "Éxito",
                    javax.swing.JOptionPane.INFORMATION_MESSAGE);

            // Limpiar formulario
            cpNombre1.setText("");
            cpUsuario1.setText("");
            cpContraseña.setText("");
            cpCedula.setText("");
            cpCorreo.setText("");
            cpNombre1.requestFocus();
             new Vista.FrmMenu().setVisible(true);
    this.dispose();

        } else {
            // Mostrar error del controlador
            javax.swing.JOptionPane.showMessageDialog(this,
                    resultado,
                    "Error al registrar",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btnRegistrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmRegistrarse().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JTextField cpCedula;
    private javax.swing.JPasswordField cpContraseña;
    private javax.swing.JTextField cpCorreo;
    private javax.swing.JTextField cpNombre1;
    private javax.swing.JTextField cpUsuario1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
